package com.dewijones92.totum.ytdlp.bridge

import com.dewijones92.totum.common.HttpUrl
import com.dewijones92.totum.common.SubtitleFormat
import com.dewijones92.totum.ytdlp.ExtractionResult
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Subtitle parsing at the bridge. All the filtering judgement lives here, so this is where
 * it gets pinned down: which formats survive, which languages, and what wins when the same
 * language is available both hand-written and machine-generated.
 */
class SubtitleParsingTest {

    private val url = HttpUrl.of("https://example.com/watch?v=abc")

    private fun extract(subtitlesJson: String): List<com.dewijones92.totum.common.SubtitleTrack> {
        val body = """{"ok":true,"info":{"id":"abc","title":"T","formats":[
            {"format_id":"18","ext":"mp4","vcodec":"avc1","acodec":"mp4a","url":"https://e/v.mp4"}
        ],$subtitlesJson}}"""
        return (parseExtraction(url, body) as ExtractionResult.Success).metadata.subtitles
    }

    @Test
    fun `parses an author-provided vtt track`() {
        val tracks = extract(
            """"subtitles":{"en":[{"ext":"vtt","url":"https://e/en.vtt","name":"English"}]}""",
        )

        val track = tracks.single()
        assertEquals("en", track.languageCode)
        assertEquals("English", track.label)
        assertEquals(SubtitleFormat.VTT, track.format)
        assertFalse(track.autoGenerated)
    }

    /**
     * A track in a format we can't decode would appear in the menu and then show nothing,
     * which is worse than not offering it.
     */
    @Test
    fun `drops formats the player cannot render`() {
        val tracks = extract(
            """"subtitles":{"en":[{"ext":"json3","url":"https://e/en.json3","name":"English"}],
               "fr":[{"ext":"srv3","url":"https://e/fr.srv3","name":"French"}]}""",
        )

        assertTrue(tracks.isEmpty())
    }

    @Test
    fun `keeps one track per language when several renderable formats exist`() {
        val tracks = extract(
            """"subtitles":{"en":[
                 {"ext":"vtt","url":"https://e/en.vtt","name":"English"},
                 {"ext":"srt","url":"https://e/en.srt","name":"English"}
               ]}""",
        )

        assertEquals(1, tracks.size)
    }

    @Test
    fun `marks auto-generated captions so you know what you are reading`() {
        val tracks = extract(
            """"automatic_captions":{"en":[{"ext":"vtt","url":"https://e/a.vtt","name":"English"}]}""",
        )

        val track = tracks.single()
        assertTrue(track.autoGenerated)
        assertTrue(track.label, track.label.contains("auto"))
    }

    /**
     * YouTube advertises its machine transcription translated into ~100 languages. All of
     * them in a menu is not a feature.
     */
    @Test
    fun `drops auto-captions for languages outside the kept set`() {
        val tracks = extract(
            """"automatic_captions":{
                 "en":[{"ext":"vtt","url":"https://e/en.vtt","name":"English"}],
                 "ja":[{"ext":"vtt","url":"https://e/ja.vtt","name":"Japanese"}],
                 "zu":[{"ext":"vtt","url":"https://e/zu.vtt","name":"Zulu"}]
               }""",
        )

        assertEquals(listOf("en"), tracks.map { it.languageCode })
    }

    /** Author-provided tracks are never filtered by language — someone chose to write those. */
    @Test
    fun `keeps author tracks in any language`() {
        val tracks = extract(
            """"subtitles":{"ja":[{"ext":"vtt","url":"https://e/ja.vtt","name":"Japanese"}]}""",
        )

        assertEquals(listOf("ja"), tracks.map { it.languageCode })
    }

    /** A real subtitle track makes the machine version of the same language redundant. */
    @Test
    fun `an author track beats the auto-caption for the same language`() {
        val tracks = extract(
            """"subtitles":{"en":[{"ext":"vtt","url":"https://e/en.vtt","name":"English"}]},
               "automatic_captions":{"en":[{"ext":"vtt","url":"https://e/auto.vtt","name":"English"}]}""",
        )

        val track = tracks.single()
        assertFalse(track.autoGenerated)
        assertEquals("https://e/en.vtt", track.url.value)
    }

    @Test
    fun `author tracks come before auto ones`() {
        val tracks = extract(
            """"subtitles":{"fr":[{"ext":"vtt","url":"https://e/fr.vtt","name":"French"}]},
               "automatic_captions":{"en":[{"ext":"vtt","url":"https://e/en.vtt","name":"English"}]}""",
        )

        assertEquals(listOf(false, true), tracks.map { it.autoGenerated })
    }

    /**
     * Real data from a Veritasium video: YouTube served both "English" (author) and
     * "English (Original)" keyed `en-orig`, which an exact-code comparison treats as a
     * different language and lists twice.
     */
    @Test
    fun `an author track suppresses the auto-caption of a variant of the same language`() {
        val tracks = extract(
            """"subtitles":{"en":[{"ext":"vtt","url":"https://e/en.vtt","name":"English"}]},
               "automatic_captions":{"en-orig":[{"ext":"vtt","url":"https://e/o.vtt","name":"English (Original)"}]}""",
        )

        assertEquals(listOf("en"), tracks.map { it.languageCode })
    }

    /** Also real: "Portuguese" and "Portuguese (Portugal)" machine versions of one thing. */
    @Test
    fun `only one auto-caption survives per language`() {
        val tracks = extract(
            """"automatic_captions":{
                 "pt":[{"ext":"vtt","url":"https://e/pt.vtt","name":"Portuguese"}],
                 "pt-PT":[{"ext":"vtt","url":"https://e/ptpt.vtt","name":"Portuguese (Portugal)"}]
               }""",
        )

        assertEquals(1, tracks.size)
    }

    /** Author-provided variants are a real choice, so they are not collapsed. */
    @Test
    fun `author regional variants are both kept`() {
        val tracks = extract(
            """"subtitles":{
                 "en":[{"ext":"vtt","url":"https://e/en.vtt","name":"English"}],
                 "en-GB":[{"ext":"vtt","url":"https://e/gb.vtt","name":"English (UK)"}]
               }""",
        )

        assertEquals(2, tracks.size)
    }

    @Test
    fun `a video with no captions yields none`() {
        assertTrue(extract(""""subtitles":{}""").isEmpty())
    }

    @Test
    fun `a track without a usable url is skipped rather than crashing`() {
        val tracks = extract(""""subtitles":{"en":[{"ext":"vtt","name":"English"}]}""")

        assertTrue(tracks.isEmpty())
    }
}
