package com.dewijones92.totum.ytdlp.bridge

import com.dewijones92.totum.common.HttpUrl
import com.dewijones92.totum.common.SubtitleFormat
import com.dewijones92.totum.common.SubtitleTrack
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject

/**
 * Subtitle parsing for the totum_ytdlp.py contract. Split from `BridgeJson` because all the
 * *judgement* about captions lives here — which formats and languages survive — and that is
 * a different concern from mapping yt-dlp's fields onto our types.
 */

/**
 * Subtitle tracks worth offering: author-provided ones first, then auto-generated.
 *
 * Two filters, both deliberate:
 *
 * - **Format.** A track we can't decode is worse than no track, because it appears in the
 *   menu and then shows nothing. YouTube offers `srv1`/`srv2`/`srv3`/`json3` alongside
 *   `vtt`; only the renderable ones survive [SubtitleFormat.fromExtension].
 * - **Language, for auto-captions only.** YouTube advertises its machine transcription
 *   translated into ~100 languages. All of them in a menu is not a feature, so automatic
 *   tracks are kept only for [AUTO_CAPTION_LANGUAGES], one per language, and never where an
 *   author wrote that language. Author-provided tracks are never filtered or collapsed,
 *   because someone chose to write those — including regional variants.
 *
 * The collapsing is by *base* language, which real data forced: YouTube served this video
 * both "English" (author) and "English (Original) (auto)" — keyed `en-orig`, so an
 * exact-code comparison saw a different language — plus "Portuguese" and "Portuguese
 * (Portugal)" machine versions of the same thing.
 */
public fun JsonObject.subtitleTracks(): List<SubtitleTrack> {
    val manual = (this["subtitles"] as? JsonObject).toTracks(autoGenerated = false)
    val authored = manual.map { it.baseLanguage }.toSet()
    val automatic = (this["automatic_captions"] as? JsonObject)
        .toTracks(autoGenerated = true)
        .filter { it.baseLanguage in AUTO_CAPTION_LANGUAGES }
        .filterNot { it.baseLanguage in authored }
        .distinctBy { it.baseLanguage }
    return manual + automatic
}

/**
 * yt-dlp's shape: `{"en": [{"ext": "vtt", "url": "…", "name": "English"}, …], …}`.
 *
 * One track per language: several renderable formats of the same captions are the same
 * choice to a user, so the first survives and the rest are dropped.
 */
private fun JsonObject?.toTracks(autoGenerated: Boolean): List<SubtitleTrack> =
    this?.entries?.flatMap { (language, entries) ->
        (entries as? JsonArray).orEmpty()
            .mapNotNull { entry -> (entry as? JsonObject)?.toSubtitleTrackOrNull(language, autoGenerated) }
            .take(1)
    }.orEmpty()

private fun JsonObject.toSubtitleTrackOrNull(language: String, autoGenerated: Boolean): SubtitleTrack? {
    val format = SubtitleFormat.fromExtension(stringOrNull("ext") ?: return null) ?: return null
    val url = stringOrNull("url")?.let(HttpUrl::parse) ?: return null
    val name = stringOrNull("name")?.ifBlank { null } ?: language
    return SubtitleTrack(
        languageCode = language,
        label = if (autoGenerated) "$name (auto)" else name,
        url = url,
        autoGenerated = autoGenerated,
        format = format,
    )
}

/**
 * Which languages are worth keeping machine captions for. English plus the common
 * European set — narrow on purpose; the alternative is a hundred-item menu.
 */
private val AUTO_CAPTION_LANGUAGES = setOf("en", "cy", "fr", "de", "es", "it", "pt", "nl")
