package com.dewijones92.totum.video

import com.dewijones92.totum.common.Diag
import com.dewijones92.totum.common.HttpUrl
import com.dewijones92.totum.common.SubtitleFormat
import com.dewijones92.totum.common.SubtitleTrack
import com.dewijones92.totum.domain.SkipSegment
import com.dewijones92.totum.domain.SourceId
import com.dewijones92.totum.ytdlp.ChapterInfo
import com.dewijones92.totum.ytdlp.MediaFormat
import com.dewijones92.totum.ytdlp.MediaMetadata
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File
import java.security.MessageDigest
import java.time.Instant
import kotlin.time.Duration.Companion.milliseconds

data class StoredLookup(
    val metadata: MediaMetadata,
    val sourceId: SourceId,
    val segments: List<SkipSegment>,
    val savedAtMs: Long,
)

interface LookupStore {
    fun load(watchUrl: HttpUrl): StoredLookup?
    fun save(watchUrl: HttpUrl, lookup: StoredLookup)
}

class FileLookupStore(private val dir: File, private val keep: Int = KEEP) : LookupStore {

    override fun load(watchUrl: HttpUrl): StoredLookup? {
        val file = fileFor(watchUrl)
        if (!file.exists()) return null
        return runCatching { json.decodeFromString(Stored.serializer(), file.readText()).toLookup() }
            .onFailure {
                Diag.warn("resolve", "stored lookup for ${watchUrl.value} was unreadable; removing it", it)
                file.delete()
            }
            .getOrNull()
    }

    override fun save(watchUrl: HttpUrl, lookup: StoredLookup) {
        runCatching {
            dir.mkdirs()
            val target = fileFor(watchUrl)
            val temp = File(dir, target.name + ".tmp")
            temp.writeText(json.encodeToString(Stored.serializer(), Stored.of(lookup)))
            temp.renameTo(target)
            prune()
        }.onFailure { Diag.warn("resolve", "could not store the lookup for ${watchUrl.value}", it) }
    }

    private fun prune() {
        val stored = dir.listFiles { file ->
            file.name.endsWith(
                SUFFIX
            )
        }.orEmpty().sortedByDescending { it.lastModified() }
        stored.drop(keep).forEach { it.delete() }
    }

    private fun fileFor(watchUrl: HttpUrl): File {
        val digest = MessageDigest.getInstance("SHA-1").digest(watchUrl.value.toByteArray())
        return File(dir, digest.joinToString("") { "%02x".format(it) } + SUFFIX)
    }

    @Serializable
    private data class Stored(
        val savedAtMs: Long,
        val sourceId: String,
        val segments: List<Segment>,
        val id: String,
        val title: String,
        val uploader: String?,
        val durationSeconds: Long?,
        val thumbnailUrl: String?,
        val formats: List<Format>,
        val description: String?,
        val uploaderUrl: String?,
        val chapters: List<Chapter>,
        val publishedAtEpochSeconds: Long?,
        val subtitles: List<Subtitle>,
    ) {
        fun toLookup() = StoredLookup(
            metadata = MediaMetadata(
                id = id,
                title = title,
                uploader = uploader,
                durationSeconds = durationSeconds,
                thumbnailUrl = thumbnailUrl,
                formats = formats.map { it.toFormat() },
                description = description,
                uploaderUrl = uploaderUrl,
                chapters = chapters.map { ChapterInfo(it.startSeconds, it.title) },
                publishedAt = publishedAtEpochSeconds?.let(Instant::ofEpochSecond),
                subtitles = subtitles.map {
                    SubtitleTrack(
                        it.languageCode,
                        it.label,
                        HttpUrl.of(it.url),
                        it.autoGenerated,
                        SubtitleFormat.valueOf(it.format)
                    )
                },
            ),
            sourceId = SourceId(sourceId),
            segments = segments.map { SkipSegment(it.startMs.milliseconds, it.endMs.milliseconds) },
            savedAtMs = savedAtMs,
        )

        companion object {
            fun of(lookup: StoredLookup) = with(lookup.metadata) {
                Stored(
                    savedAtMs = lookup.savedAtMs,
                    sourceId = lookup.sourceId.value,
                    segments = lookup.segments.map {
                        Segment(
                            it.start.inWholeMilliseconds,
                            it.end.inWholeMilliseconds
                        )
                    },
                    id = id,
                    title = title,
                    uploader = uploader,
                    durationSeconds = durationSeconds,
                    thumbnailUrl = thumbnailUrl,
                    formats = formats.map(Format::of),
                    description = description,
                    uploaderUrl = uploaderUrl,
                    chapters = chapters.map { Chapter(it.startSeconds, it.title) },
                    publishedAtEpochSeconds = publishedAt?.epochSecond,
                    subtitles = subtitles.map {
                        Subtitle(
                            it.languageCode,
                            it.label,
                            it.url.value,
                            it.autoGenerated,
                            it.format.name
                        )
                    },
                )
            }
        }
    }

    @Serializable
    private data class Format(
        val formatId: String,
        val container: String,
        val width: Int?,
        val height: Int?,
        val hasVideo: Boolean,
        val hasAudio: Boolean,
        val fileSizeBytes: Long?,
        val url: String?,
        val videoCodec: String?,
        val audioCodec: String?,
        val language: String?,
        val languagePreference: Int?,
    ) {
        fun toFormat() = MediaFormat(
            formatId, container, width, height, hasVideo, hasAudio, fileSizeBytes, url,
            videoCodec, audioCodec, language, languagePreference,
        )

        companion object {
            fun of(f: MediaFormat) = Format(
                f.formatId, f.container, f.width, f.height, f.hasVideo, f.hasAudio, f.fileSizeBytes, f.url,
                f.videoCodec, f.audioCodec, f.language, f.languagePreference,
            )
        }
    }

    @Serializable
    private data class Chapter(val startSeconds: Double, val title: String)

    @Serializable
    private data class Subtitle(
        val languageCode: String,
        val label: String,
        val url: String,
        val autoGenerated: Boolean,
        val format: String,
    )

    @Serializable
    private data class Segment(val startMs: Long, val endMs: Long)

    private companion object {
        const val KEEP = 30
        const val SUFFIX = ".lookup.json"
        val json = Json { ignoreUnknownKeys = true }
    }
}
